# Generated by Django 5.0.3 on 2024-04-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='folder',
            field=models.FileField(upload_to='journals'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
