# Generated by Django 5.0.3 on 2024-04-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repository', '0003_alter_journal_folder_alter_journal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
